---
# 服务配置，支持无限数量的分组和每个分组内的无限服务

- Company:
    - 权限 & 工作流:
        - 易链:
            icon: /icons/company-elink.png
            href: https://elink.thundersoft.com/
            ping: elink.thundersoft.com
        - 集团工作平台:
            icon: /icons/company.ico
            href: http://i.thundersoft.com/
            ping: i.thundersoft.com
    - Code:
        - OpenGrok:
            icon: /icons/company-opengrok.png
            href: http://192.168.6.247:8080/source/
            ping: 192.168.6.247
        - Gerrit:
            icon: /icons/company-gerrit.ico
            href: http://10.2.12.42/gerrit/dashboard/self
            ping: 10.2.12.42
        - Jenkins:
            icon: /icons/company-jenkins.svg
            href: http://10.0.54.250:8080/
            ping: 10.0.54.250
    - 资料:
        - 高通文档:
            icon: /icons/company-qualcomm.png
            href: https://createpoint.qti.qualcomm.com/chipcenter/#search/global/searchArgs/rows||10||sortField||score||sortOrder||desc||fq_facetChipsets||QAM8295P
            ping: createpoint.qti.qualcomm.com
        - QNX 7.1:
            icon: /icons/company-qnx7.1.png
            href: https://www.qnx.com/developers/docs/7.1
            ping: www.qnx.com
        - QNX 8.0:
            icon: /icons/company-qnx8.0.png
            href: https://www.qnx.com/developers/docs/8.0
            ping: www.qnx.com
        - 飞书个性签名:
            icon: /icons/company-documents.png
            href: https://ituhdo1hkk.feishu.cn/docx/Lw0xdER0qoExN3xgP7Fc9AItnob
            ping: ituhdo1hkk.feishu.cn

- Anime & movie:
    - 资讯:
        - 新番表:
            icon: /icons/anime-new_anime.ico
            href: https://acgsecrets.hk/
            ping: acgsecrets.hk
        - 萌娘百科:
            icon: /icons/anime-meng.ico
            href: https://zh.moegirl.org.cn/
            ping: zh.moegirl.org.cn
    - Anime:
        - SubsPlease:
            icon: /icons/anime-subsplease.ico
            href: https://subsplease.org/
            ping: subsplease.org
        - 漫猫动漫:
            icon: /icons/anime-comicat.ico
            href: http://3.comicat.115000.xyz/
            ping: 3.comicat.115000.xyz
        - VCB-Studio:
            icon: /icons/anime-vcb.png
            href: https://vcb-s.com/
            ping: vcb-s.com
        - NYAA:
            icon: /icons/anime-nyaa.png
            href: https://nyaa.si/
            ping: nyaa.si
        - ACG:
            icon: /icons/anime-acg.ico
            href: https://acg.rip/
            ping: acg.rip
        - 东京图书馆:
            icon: /icons/anime-tokyo.png
            href: https://tokyo-tosho.net/
            ping: tokyo-tosho.net
    - 字幕:
        - OpenSubTitles:
            icon: /icons/anime-opensubtitles.ico
            href: https://www.opensubtitles.org/
            ping: www.opensubtitles.org

- Cloud Server:
    - Tools:
        - DNS 解析:
            icon: /icons/cloud-dns.ico
            href: https://dnsnext.console.aliyun.com/authoritative/domains/vaciller.top
            ping: dnsnext.console.aliyun.com
        - SSL 证书:
            icon: /icons/cloud-ssl.png
            href: https://console.cloud.tencent.com/ssl
            ping: console.cloud.tencent.com
    - Docker:
        - CasaOS:
            icon: /icons/docker-casaos.png
            href: https://casaos.vaciller.top/
            ping: casaos.vaciller.top
        - CasaOS-MAC-Mini-M4:
            icon: /icons/docker-casaos.png
            href: https://casaos-mac.vaciller.top/
            ping: casaos-mac.vaciller.top
        - CineMore:
            icon: /icons/docker-cinemore.ico
            href: https://cinemore.vaciller.top/
            ping: cinemore.vaciller.top
    - FRP:
        - Frps:
            icon: /icons/frp-frps.png
            href: https://frps.vaciller.top/
            ping: frps.vaciller.top
        - Frpc:
            icon: /icons/frp-frpc.png
            href: https://frpc.vaciller.top/
            ping: frpc.vaciller.top

- DailyKit:
    - Code:
        - github:
            icon: /icons/code-github.png
            href: https://github.com/VaillerTeeter?tab=repositories
            ping: github.com
    - AI:
        - Kimi:
            icon: /icons/ai-kimi.ico
            href: https://www.kimi.com/
            ping: www.kimi.com
        - DeepSeek:
            icon: /icons/ai-deepseek.png
            href: https://chat.deepseek.com/
            ping: chat.deepseek.com
    - Money:
        - Paypal:
            icon: /icons/money-paypal.ico
            href: https://www.paypal.com/
            ping: www.paypal.com
    - Computer:
        - Office Tool Plus:
            icon: /icons/computer-office.ico
            href: https://otp.landian.vip/
            ping: otp.landian.vip
        - 系统镜像:
            icon: /icons/computer-image.ico
            href: https://next.itellyou.cn/
            ping: next.itellyou.cn
        - VPN-雷霆:
            icon: /icons/computer-leiting.ico
            href: https://vopqaq93yh4b.ltltltltltltlt.top/
            ping: vopqaq93yh4b.ltltltltltltlt.top
