---
# 信息类小部件设置
# 资源详情
# 官方文档：https://gethomepage.dev/widgets/info/resources/
- resources:
    # 分组标题；可复用多次生成多个卡片
    # label: xxx
    cpu: true
    memory: true
    disk:
      - /
      - /Volumes/App
      - /Volumes/TerraMas-4T-1
      - /Volumes/TerraMas-4T-2
      - /Volumes/TerraMas-14T-1
      - /Volumes/TerraMas-14T-2
      - /Volumes/TerraMas-14T-3
      - /Volumes/TerraMas-14T-4
    # bytes/bbytes 1000/1024
    diskUnits: bbytes
    cputemp: true
    tempmin: 0
    tempmax: 100
    # metric/imperial °C/°F
    units: metric
    # 运行时间
    uptime: true
    network: true
    # 展开卡片，额外显示绝对值
    expanded: true
    # 轮询间隔，ms
    refresh: 3000

# 搜索
# 官方文档：https://gethomepage.dev/widgets/info/search/
- search:
    # google, duckduckgo, bing, baidu, brave or custom
    provider: [duckduckgo, google, bing, brave]
    # 页面加载后自动聚焦搜索框
    focus: true
    # _blank：新标签页
    # _self：当前页面
    # _top：新窗口
    target: _blank
    # 显示互联网搜索的搜索建议
    showSearchSuggestions: true

# 天气插件
# 官方文档：https://gethomepage.dev/widgets/info/openmeteo/
- openmeteo:
    # 显示的文本文字
    # label: 当前位置
    # 坐标，无此项则显示定位地址天气
    # latitude: 50.449684
    # longitude: 30.525026
    # metric/imperial °C/°F
    units: metric
    # API 结果缓存时间，单位分钟
    cache: 5
    format:
      maximumFractionDigits: 1
